### ISSUE TITLE
cp: cannot stat '/bin/ngrok': No such file or directory

### ISSUE THREAD

**Issue by sefsters77** [Cesar-Hack-Gray/FotoSploit#1]
cp: cannot stat '/bin/ngrok': No such file or directory
[+] FOTO => No se pudo agregar la foto

help me please

**Comment by fakartstore** [comment]
o2-01:~/FotoSploit# ./FotoSploit
-bash: ./FotoSploit: /bin/env: bad interpreter: No such file or directory

**Comment by Cesar-Hack-Gray** [comment]
Thanks for the report now I get to it
