### ISSUE TITLE
No funciona en arch 

### ISSUE THREAD

**Issue by Yisus7u7** [Cesar-Hack-Gray/FotoSploit#22]
Hola, trate de usarlo en arch linux, instale ngrok y lo puse en la carpeta, tambien las dependencias (python 3, php, openssh,), pero cuando abro el link no sale nada, no funciona en arch?

**Comment by Cesar-Hack-Gray** [comment]
Hola te saluda Cesar Hack Gray


Hola bro bueno segun lo que entendi todo sale bien te da el link de ngrok
pero cuando lo pegas en tu navegador no sale nada sierto, FotoSploit esta
hecho directamente para termux bro intente hacerla para kali y otros
terminales pero se me iso imposible amigo pero seguire trabajando en ello
por lo tanto funciona al 100 en termux por si deseas usarla desde aya

Te saluda Cesar y Mickey.....

**Comment by Yisus7u7** [comment]
Muchas gracias bro, pero estoy en pc, no en termux, y me gusta FotoSploit por ser simple, rápida y eficaz, aparte que los links no se si te has dado cuanta pero ahora tambien funcionan en messenger

**Comment by Yisus7u7** [comment]
La otra es que, me podrías dar acceso al código fuente?, para hacer una compilación para arch o espero a que hagas algún compilación vos?

**Comment by Cesar-Hack-Gray** [comment]
Si lo del enviar en messenger si funciona pero desde la web de facebook
porque en messenger apk no saca ma foto :"(

Amm quieres el codigo fuente

**Comment by Yisus7u7** [comment]
Pues para hacer una compilación para arch, o si loa vas a hacer tu puedo esperar

**Comment by Cesar-Hack-Gray** [comment]
Siempre ando ocupado trabajando man me tardaria mas

Como se que no robaras el scritp

**Comment by Yisus7u7** [comment]
De que me sirve robar tu script, no tiene sentido, solo lo necesito pero estoy en arch :C

**Comment by Cesar-Hack-Gray** [comment]
En el sentido de que puedes modificarla y agregarle tu nombre cambiarle de
colores y subirlo en un repositorio que fue hecho por ti

Dame una buena razon para dartela
Escribeme

+502 32616323

**Comment by Yisus7u7** [comment]
Listo bro, ya te escribí

**Comment by Yisus7u7** [comment]
Te escribi por WhatsApp

**Comment by soynoob3384** [comment]
Este oye te equivocaste de persona

**Comment by Yisus7u7** [comment]
?

**Comment by soynoob3384** [comment]
Oye este por qué me mandas correos que nesecitas yo no nesecito dudas

**Comment by Yisus7u7** [comment]
No te entiendo

**Comment by Yisus7u7** [comment]
Yo no te e escrito

**Comment by 3l-tech** [comment]
Hi my name is 3L-TECH

A Ter, 23 de mar de 2021, 15:35, Yisus7u7 ***@***.***>
escreveu:
